// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SOAT1StackGoLang/msvc-payments/pkg/api (interfaces: PaymentAPI)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/api_mocks.go -package=mocks github.com/SOAT1StackGoLang/msvc-payments/pkg/api PaymentAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	api "github.com/SOAT1StackGoLang/msvc-payments/pkg/api"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentAPI is a mock of PaymentAPI interface.
type MockPaymentAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentAPIMockRecorder
}

// MockPaymentAPIMockRecorder is the mock recorder for MockPaymentAPI.
type MockPaymentAPIMockRecorder struct {
	mock *MockPaymentAPI
}

// NewMockPaymentAPI creates a new mock instance.
func NewMockPaymentAPI(ctrl *gomock.Controller) *MockPaymentAPI {
	mock := &MockPaymentAPI{ctrl: ctrl}
	mock.recorder = &MockPaymentAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentAPI) EXPECT() *MockPaymentAPIMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPaymentAPI) CreatePayment(arg0 api.CreatePaymentRequest) (api.CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", arg0)
	ret0, _ := ret[0].(api.CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPaymentAPIMockRecorder) CreatePayment(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPaymentAPI)(nil).CreatePayment), arg0)
}

// GetPayment mocks base method.
func (m *MockPaymentAPI) GetPayment(arg0 api.GetPaymentRequest) (api.GetPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", arg0)
	ret0, _ := ret[0].(api.GetPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockPaymentAPIMockRecorder) GetPayment(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockPaymentAPI)(nil).GetPayment), arg0)
}
